# Dossiers
CODE := $(shell pwd)
BUILD = build/

src:
	gcc -wall src/morpions.c –o $(BUILD)/morp

	gcc -c -Wall main.c
gcc -o prog main.o structure.o operation.o

$(BUILD)/morp: src/morpion.c
    gcc src/morpions.c –o $@