all: pb1 pb2 pb3 pb4 pb5 pb6 pb7 pb8 pb9 pb10

pb1:
	python3 algo/pb1_entiers-multiple-3-5.py
pb2:
	python3 algo/pb2_entiers-fibonacci-pair.py
pb3:
	python3 algo/pb3_plus-grand-facteur-premier.py
pb4:
	python3 algo/pb4_plus-grand-produit-facteurs.py
pb5:
	python3 algo/pb5_plus-petit-facteur-1-20.py
pb6:
	python3 algo/pb6_différence-carrés-100.py
pb7:
	python3 algo/pb76_1001-premier.py
pb8: 
	python3 algo/pb8_produit-5-chiffres.py
pb9: 
	python3 algo/pb9_3-pythagore.py
pb10: 
	python3 algo/pb10_somme-premiers-10-millions.py
